"""Robokassa settings"""

ROBOKASSA_LOGIN = 'Login'
ROBOKASSA_PASSWORD1 = 'Password1'
ROBOKASSA_PASSWORD2 = 'Password2'
ROBOKASSA_USE_POST = True
ROBOKASSA_STRICT_CHECK = True
ROBOKASSA_TEST_MODE = False
ROBOKASSA_EXTRA_PARAMS = []
