# Generated by Django 3.2.8 on 2021-11-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='final_price',
        ),
    ]
